/*
 * SpectrumCanvas.java
 *
 * Created on October 23, 2001, 4:03 PM
 */

package dwvisser.nuclear.graphics;
import java.awt.*;
import java.awt.geom.*;
import java.awt.font.*;
import javax.swing.*;

/**
 *
 * @author  dwvisser
 */
public class SpectrumCanvas extends JPanel {

    double[] radii,Ex;
    RadiusRange range;
    
    /** Creates new form SpectrumCanvas */
    public SpectrumCanvas(RadiusRange rr) {
        initComponents();
        this.range=rr;
        setBackground(Color.white);
        setBorder(BorderFactory.createLineBorder(Color.blue,1));
        setOpaque(true);
    }
    
    public void setRadii(double [] radii){
        this.radii=radii;
    }
    
    public void setEx(double [] Ex){
        this.Ex=Ex;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        setLayout(new java.awt.BorderLayout());

    }//GEN-END:initComponents

    public void paintComponent(Graphics graphics) {
        Line2D line;
        //System.out.println("painting with rho from "+range.getRhoMin()+" to "+
        //range.getRhoMax());
        Graphics2D g2=(Graphics2D)graphics;
        FontRenderContext frc=g2.getFontRenderContext();
        Dimension d=getSize();
        double length=range.getRhoMax()-range.getRhoMin();
        //g2.setPaint(Color.blue);
        //g2.draw(new Line2D.Double(0,0,d.width,0));
        //g2.draw(new Line2D.Double(d.width,0,d.width,d.height));
        //g2.draw(new Line2D.Double(d.width,d.height,0,d.height));
        //g2.draw(new Line2D.Double(0,d.height,0,0));
        g2.setPaint(Color.darkGray);
        double lastXcoord=d.width;
        for (int i=0; i<radii.length;i++){
            //x coordinate from left
            if (radii[i] > range.getRhoMin() && radii[i] < range.getRhoMax()){
                String sEx = Ex[i]+" ";
                double xfrac = (radii[i]-range.getRhoMin())/length;
                double xcoord = xfrac*d.width;
                double diff = lastXcoord-xcoord;
                Rectangle2D stringBounds=g2.getFont().getStringBounds(sEx,frc);
                double lineBottom;
                if (diff >= stringBounds.getWidth()) {
                    g2.drawString(sEx,(float)xcoord,(float)(d.height-
                    stringBounds.getHeight()/10));
                    lastXcoord=xcoord;
                    lineBottom = d.height-stringBounds.getHeight();
                } else {
                    lineBottom = d.height-2*stringBounds.getHeight();
                }
                line = new Line2D.Double(xcoord,0,xcoord,lineBottom);
                g2.draw(line);
            }
        }
    }    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
