package dwvisser.analysis;

/**
 *
 * @author
 * @version
 */
public class MomentumPlotter extends javax.swing.JFrame {

  /** Initializes the Form */
  public MomentumPlotter() {
    initComponents ();
    pack ();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the FormEditor.
   */
  private void initComponents () {//GEN-BEGIN:initComponents
    addWindowListener (new java.awt.event.WindowAdapter () {
        public void windowClosing (java.awt.event.WindowEvent evt) {
          exitForm (evt);
        }
      }
    );
    getContentPane ().setLayout (new java.awt.BorderLayout ());

    plotPanel = new javax.swing.JPanel ();
    plotPanel.setLayout (new java.awt.FlowLayout ());

    getContentPane ().add (plotPanel, "Center");

    actionPanel = new javax.swing.JPanel ();
    actionPanel.setLayout (new java.awt.FlowLayout ());

      addReaction = new javax.swing.JButton ();
      addReaction.setText ("Add Reaction");
      addReaction.addActionListener (new java.awt.event.ActionListener () {
          public void actionPerformed (java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed (evt);
          }
        }
      );
      actionPanel.add (addReaction);

      jButton1 = new javax.swing.JButton ();
      jButton1.setText ("Remove Reaction");
      actionPanel.add (jButton1);

      jPanel1 = new javax.swing.JPanel ();
      jPanel1.setLayout (new java.awt.FlowLayout ());

        jLabel1 = new javax.swing.JLabel ();
        jLabel1.setText ("Beam Energy [MeV]");
        jPanel1.add (jLabel1);

        tBeamEnergy = new javax.swing.JTextField ();
        tBeamEnergy.setColumns (6);
        tBeamEnergy.setText ("100.0");
        jPanel1.add (tBeamEnergy);

      actionPanel.add (jPanel1);

      jLabel2 = new javax.swing.JLabel ();
      jLabel2.setText ("Theta [deg]");
      actionPanel.add (jLabel2);

      tTheta = new javax.swing.JTextField ();
      tTheta.setColumns (6);
      tTheta.setText ("8.0");
      actionPanel.add (tTheta);

      jLabel3 = new javax.swing.JLabel ();
      jLabel3.setText ("B Field [kG]");
      actionPanel.add (jLabel3);

      tField = new javax.swing.JTextField ();
      tField.setColumns (6);
      tField.setText ("1.0");
      actionPanel.add (tField);

    getContentPane ().add (actionPanel, "South");

    rangePanel = new javax.swing.JPanel ();
    rangePanel.setLayout (new java.awt.GridLayout (4, 1));

      jLabel4 = new javax.swing.JLabel ();
      jLabel4.setText ("Minumum Rho [cm]");
      rangePanel.add (jLabel4);

      tRhoMin = new javax.swing.JTextField ();
      tRhoMin.setText ("70.0");
      rangePanel.add (tRhoMin);

      jLabel5 = new javax.swing.JLabel ();
      jLabel5.setText ("Maximum Rho [cm]");
      rangePanel.add (jLabel5);

      tRhoMax = new javax.swing.JTextField ();
      tRhoMax.setText ("90.0");
      rangePanel.add (tRhoMax);

    getContentPane ().add (rangePanel, "East");

  }//GEN-END:initComponents

  private void jButton1ActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    // Add your handling code here:
  }//GEN-LAST:event_jButton1ActionPerformed

  /** Exit the Application */
  private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
    System.exit (0);
  }//GEN-LAST:event_exitForm


// Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel plotPanel;
  private javax.swing.JPanel actionPanel;
  private javax.swing.JButton addReaction;
  private javax.swing.JButton jButton1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JTextField tBeamEnergy;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JTextField tTheta;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JTextField tField;
  private javax.swing.JPanel rangePanel;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JTextField tRhoMin;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JTextField tRhoMax;
// End of variables declaration//GEN-END:variables


  public static void main(java.lang.String[] args) {
    new MomentumPlotter ().show ();
  }

}
